# 数据库连接参数
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/????
    username: ????
    password: ????
  liquibase:
    # 自定义Liquibase路径
    change-log: classpath:/database/master.xml
    # 是否启用Liquibase
    enabled: true

mybatis-plus:
  mapper-locations: jasmine/**/*.xml

app:
  swagger:
    version: 0.1
    title: 茉莉花
    base-package: jasmine