spring:
  # 数据库连接参数
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/????
    username: ????
    password: ????
    type: com.zaxxer.hikari.HikariDataSource
  hikari:
    # 最小空闲连接数量
    minimum-idle: 10
    # 连接超时时间
    connection-timeout: 30000
  liquibase:
    # 自定义Liquibase路径
    change-log: classpath:/database/master.xml
    # 是否启用Liquibase
    enabled: true
  redis:
    host: 127.0.0.1
    port: 6379
  # 消息队列
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

# 配置日志
logging:
  level:
    jasmine: debug

mybatis-plus:
  # 自定义 mapper 文件路径
  mapper-locations: jasmine/**/*.xml

app:
  # 配置 swagger 文档
  swagger:
    version: 0.1
    title: 茉莉花
    base-package: jasmine
  rabbitmq:
    enabled: false
