spring:
  # 数据库连接参数
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/????
    username: ????
    password: ????
    type: com.zaxxer.hikari.HikariDataSource
  hikari:
    # 最小空闲连接数量
    minimum-idle: 10
    # 连接超时时间
    connection-timeout: 30000
  liquibase:
    # 自定义Liquibase路径
    change-log: classpath:/database/master.xml
    # 是否启用Liquibase
    enabled: true
  redis:
    host: 127.0.0.1
    port: 6379
  # 消息队列
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  web:
    resources:
      # 静态资源路径
      static-locations: classpath:/webapp/public/
  thymeleaf:
    # thymeleaf模板前缀
    prefix: classpath:/webapp/template/

# 配置日志
logging:
  level:
    jasmine: debug

mybatis-plus:
  # 自定义 mapper 文件路径
  mapper-locations: jasmine/**/*.xml

# API文档
springdoc:
  packages-to-scan: jasmine.demo

# 任务调度
#xxl:
#  job:
#    admin:
#      addresses: http://127.0.0.1:8080/xxl-job-admin
#    access-token:
#    executor:
#      app-name: jasmine
#      address:
#      ip:
#      port: 9999
#      log-path: /data/applogs/xxl-job/jobhandler
#      log-retention-days: 30

jasmine:
  message-queue:
    # 是否发送消息到消息队列
    publisher:
      enabled: false
    # 是否监听消息队列的消息
    consumer:
      enabled: false
  xxl:
    job:
      # 是否启用 xxl-job 任务调度
      enabled: false
  data:
    tenant:
      # 是否启用租户拦截器
      enabled: true
    # 数据加密
    crypto:
      password: password1
      salt: salt1
  security:
    authorization:
      # 访问策略
      strategy: default
    # 静态资源
    staticLocations: /static/**,/swagger-ui/**

app:
  message-queue:
    rabbitmq:
      # 是否自动创建交换器和队列
      auto-declare: false
