spring:
  # 数据库连接参数
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/????
    username: ????
    password: ????
    type: com.zaxxer.hikari.HikariDataSource
  hikari:
    # 最小空闲连接数量
    minimum-idle: 10
    # 连接超时时间
    connection-timeout: 30000
  liquibase:
    # 自定义Liquibase路径
    change-log: classpath:/database/master.xml
    # 是否启用Liquibase
    enabled: true
  redis:
    host: 127.0.0.1
    port: 6379
  # 消息队列
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  web:
    resources:
      # 静态资源路径
      static-locations: classpath:/webapp/public/
  thymeleaf:
    # thymeleaf模板前缀
    prefix: classpath:/webapp/template/

# 配置日志
logging:
  level:
    jasmine: debug

mybatis-plus:
  # 自定义 mapper 文件路径
  mapper-locations: jasmine/**/*.xml

# 任务调度
#xxl:
#  job:
#    admin:
#      addresses: http://127.0.0.1:8080/xxl-job-admin
#    accessToken:
#    executor:
#      appname: jasmine
#      address:
#      ip:
#      port: 9999
#      logpath: /data/applogs/xxl-job/jobhandler
#      logretentiondays: 30

jasmine:
  # 配置 swagger 文档
  swagger:
    version: 0.1
    title: 茉莉花
    base-package: jasmine
  message-queue:
    # 是否发送消息到消息队列
    publisher:
      enabled: false
    # 是否监听消息队列的消息
    consumer:
      enabled: false
  xxl:
    job:
      # 是否启用 xxl-job 调度任务
      enabled: false

app:
  rabbitmq:
    # 是否自动创建交换器和队列
    auto-declare: false